<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputItemType>Analyzer</OutputItemType>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="sharpsnmppro.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Lextm.SharpSnmpLib" VersionOverride="13.0.0-beta.2" />
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="SharpSnmpPro.Mib" Condition="!Exists('..\..\..\SharpSnmpPro.Mib\SharpSnmpPro.Mib.csproj')" />
  </ItemGroup>

  <!-- Reference SharpSnmpPro.Mib and ensure it's copied to the output -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharpSnmpPro.Mib\SharpSnmpPro.Mib.csproj" Condition="Exists('..\..\..\SharpSnmpPro.Mib\SharpSnmpPro.Mib.csproj')">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\SharpSnmpPro.Mib.Extensions\SharpSnmpPro.Mib.Extensions.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
